openapi: 3.0.3
info:
  title: Authentication API
  description: User authentication endpoints for signup and signin
  version: 1.0.0
  contact:
    name: Todo Application Team

servers:
  - url: http://localhost:8000
    description: Local development server
  - url: https://api.todo-app.example.com
    description: Production server

paths:
  /api/auth/signup:
    post:
      summary: Create new user account
      description: Register a new user with email and password. Returns user information and sets JWT token in httpOnly cookie.
      operationId: signup
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address (must be unique)
                  example: alice@example.com
                  minLength: 5
                  maxLength: 255
                password:
                  type: string
                  format: password
                  description: User's password (minimum 8 characters)
                  example: password123
                  minLength: 8
                  maxLength: 128
                name:
                  type: string
                  description: User's display name (optional)
                  example: Alice
                  maxLength: 255
      responses:
        '201':
          description: User account created successfully
          headers:
            Set-Cookie:
              description: JWT token in httpOnly cookie
              schema:
                type: string
                example: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...; HttpOnly; Secure; SameSite=Strict; Max-Age=86400
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Unique user identifier (UUID)
                    example: 550e8400-e29b-41d4-a716-446655440000
                  email:
                    type: string
                    format: email
                    example: alice@example.com
                  name:
                    type: string
                    nullable: true
                    example: Alice
                  created_at:
                    type: string
                    format: date-time
                    example: 2026-02-08T20:30:00Z
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                invalid_email:
                  value:
                    detail: Invalid email format
                short_password:
                  value:
                    detail: Password must be at least 8 characters
        '409':
          description: Email already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: Email already registered

  /api/auth/signin:
    post:
      summary: Sign in to existing account
      description: Authenticate user with email and password. Returns user information and sets JWT token in httpOnly cookie.
      operationId: signin
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                  example: alice@example.com
                password:
                  type: string
                  format: password
                  description: User's password
                  example: password123
      responses:
        '200':
          description: Authentication successful
          headers:
            Set-Cookie:
              description: JWT token in httpOnly cookie
              schema:
                type: string
                example: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...; HttpOnly; Secure; SameSite=Strict; Max-Age=86400
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Unique user identifier (UUID)
                    example: 550e8400-e29b-41d4-a716-446655440000
                  email:
                    type: string
                    format: email
                    example: alice@example.com
                  name:
                    type: string
                    nullable: true
                    example: Alice
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: Email and password are required
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: Invalid email or password

  /api/auth/signout:
    post:
      summary: Sign out of current session
      description: Invalidate JWT token by clearing the httpOnly cookie
      operationId: signout
      tags:
        - Authentication
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Sign out successful
          headers:
            Set-Cookie:
              description: Clear JWT token cookie
              schema:
                type: string
                example: token=; HttpOnly; Secure; SameSite=Strict; Max-Age=0
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Signed out successfully

  /api/auth/me:
    get:
      summary: Get current user information
      description: Retrieve authenticated user's profile information
      operationId: getCurrentUser
      tags:
        - Authentication
      security:
        - cookieAuth: []
        - bearerAuth: []
      responses:
        '200':
          description: User information retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: 550e8400-e29b-41d4-a716-446655440000
                  email:
                    type: string
                    format: email
                    example: alice@example.com
                  name:
                    type: string
                    nullable: true
                    example: Alice
                  created_at:
                    type: string
                    format: date-time
                    example: 2026-02-08T20:30:00Z
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: Missing or invalid authentication token

components:
  schemas:
    Error:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Human-readable error message
          example: Invalid email or password

  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
      description: JWT token stored in httpOnly cookie
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token in Authorization header (Bearer token)

tags:
  - name: Authentication
    description: User authentication and session management
